/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Vetle (https://sketchfab.com/arja)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/trees-and-foliage-c3423a86515444a2b323d422ac16e710
title: Trees and foliage
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.MASH3_ReproMesh1_m_plants_0.geometry} material={materials.m_plants} />
          <mesh geometry={nodes.MASH3_ReproMesh1_ground_0.geometry} material={materials.ground} />
          <mesh geometry={nodes.MASH3_ReproMesh1_m_leaves_0.geometry} material={materials.m_leaves} />
          <mesh geometry={nodes.MASH3_ReproMesh1_m_tree_0.geometry} material={materials.m_tree} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
