/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Siesta (https://sketchfab.com/siesta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rock-b66d5b63deb447299ca3effa904bc789
title: Rock
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rock({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rock/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow geometry={nodes.Object_2.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/rock/scene.gltf')
